### ISSUE TITLE
error [ MissingPluginException ]

### ISSUE THREAD

**Issue by Junesui** [Fintasys/emoji_picker_flutter#98]
E/flutter (19326): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method checkAvailability on channel emoji_picker_flutter)
E/flutter (19326): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (19326): <asynchronous suspension>
E/flutter (19326): #1      EmojiPickerInternalUtils._getPlatformAvailableEmoji (package:emoji_picker_flutter/src/emoji_picker_internal_utils.dart:113:23)
E/flutter (19326): <asynchronous suspension>
E/flutter (19326): #2      EmojiPickerInternalUtils._getAvailableEmojis (package:emoji_picker_flutter/src/emoji_picker_internal_utils.dart:56:16)
E/flutter (19326): <asynchronous suspension>
E/flutter (19326): #3      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
E/flutter (19326): <asynchronous suspension>
E/flutter (19326): #4      EmojiPickerInternalUtils.getAvailableCategoryEmoji (package:emoji_picker_flutter/src/emoji_picker_internal_utils.dart:91:32)
E/flutter (19326): <asynchronous suspension>
E/flutter (19326): #5      EmojiPickerState._updateEmojis (package:emoji_picker_flutter/src/emoji_picker.dart:281:9)
E/flutter (19326): <asynchronous suspension>
E/flutter (19326): 

### MY Code
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: EmojiPicker(
            onEmojiSelected: (category, emoji) {
              // Do something when emoji is tapped (optional)
            },
            onBackspacePressed: () {
              // Do something when the user taps the backspace button (optional)
            },
            textEditingController:
                _controller, // pass here the same [TextEditingController] that is connected to your input field, usually a [TextFormField]
            config: Config(
              columns: 7,
              emojiSizeMax: 32 *
                  (Platform.isIOS
                      ? 1.30
                      : 1.0), // Issue: https://github.com/flutter/flutter/issues/28894
              verticalSpacing: 0,
              horizontalSpacing: 0,
              gridPadding: EdgeInsets.zero,
              initCategory: Category.RECENT,
              bgColor: const Color(0xFFF2F2F2),
              indicatorColor: Colors.blue,
              iconColor: Colors.grey,
              iconColorSelected: Colors.blue,
              progressIndicatorColor: Colors.blue,
              backspaceColor: Colors.blue,
              skinToneDialogBgColor: Colors.white,
              skinToneIndicatorColor: Colors.grey,
              enableSkinTones: true,
              showRecentsTab: true,
              recentsLimit: 28,
              noRecents: const Text(
                'No Recents',
                style: TextStyle(fontSize: 20, color: Colors.black26),
                textAlign: TextAlign.center,
              ),
              tabIndicatorAnimDuration: kTabScrollDuration,
              categoryIcons: const CategoryIcons(),
              buttonMode: ButtonMode.MATERIAL,
            ),
          ),
        ),
      ),
    );
  }
```

**Comment by Junesui** [comment]
1
